version: '3.9'
services:
  web:
    container_name: web
    build:
      context: ./docker/web/dev
    depends_on:
      - db
    env_file:
      - .env.local
    volumes:
      - ./symfony:/var/www/html/
      - ~/.composer:/var/composer:cached
      - ./docker/web/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      - ./docker/web/dev/php.ini:/usr/local/etc/php/php.ini
      - ./docker/web/dev/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "80:80"
  db:
    container_name: db
    image: mariadb:10.3.31
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    env_file:
      - .env.local
    ports:
      - "3306:3306"
  redis:
    container_name: redis
    image: redis:5-alpine
    ports:
      - "6379:6379"
  node:
    container_name: node
    image: node:20
    volumes:
      - './symfony:/usr/app'
    restart: on-failure
    entrypoint: "tail -f /dev/null"
    working_dir: "/usr/app"
    ports:
      - "8083:8083"
volumes:
  db_data: {}
